### PR TITLE
ENH: Remove placeholder class MinimalStandardRandomVariateGenerator

### PR DESCRIPTION
**Pull request by dzenanz**
This class is generated by: https://github.com/InsightSoftwareConsortium/ITKModuleTemplate. Removing it now to reduce confusion.

### CODE REVIEW

**Comment by aylward** [comment]
Please remove commit mentioning numfocus.  This was Kitware funded work.

**Review by aylward — DISMISSED** [review]
Should remain a Kitware project.

**Comment by dzenanz** [comment]
Without it, CI test fails: https://open.cdash.org/test/1210282464:
```log
/home/runner/work/itkARGUS/itkARGUS/include/itkResampleImageUsingMapFilter.h:3: error: Header mismatch: Kitware (NumFOCUS) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/itkARGUS/itkARGUS/include/itkResampleImageUsingMapFilter.hxx:3: error: Header mismatch: Kitware (NumFOCUS) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/itkARGUS/itkARGUS/include/itkSegmentConnectedComponents.h:3: error: Header mismatch: Kitware (NumFOCUS) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/itkARGUS/itkARGUS/include/itkSegmentConnectedComponents.hxx:3: error: Header mismatch: Kitware (NumFOCUS) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/itkARGUS/itkARGUS/src/placeholder.cxx:1: error: The header is incomplete
/home/runner/work/itkARGUS/itkARGUS/src/placeholder.cxx:0: error: No new line at the end of file
/home/runner/work/itkARGUS/itkARGUS/test/itkResampleImageUsingMapFilterTest.cxx:3: error: Header mismatch: Kitware (NumFOCUS) : Utilities/KWStyle/ITKHeader.h
```
If we want to avoid this change, we probably need to disable header check via override config file.

**Comment by dzenanz** [comment]
Clean CI now 😄

**Comment by dzenanz** [comment]
I disabled header checking, so there is no need to change Kitware copyright to NumFOCUS. Please re-review, and if happy, merge.

**Review by aylward — COMMENTED** [review]
Thanks!

Does this include the wrapping/*.py files into the PyPi module?

**Comment by dzenanz** [comment]
It does no changes related to that, so no. Merging, and we will look into that separately.

**Pull request merged**
